import './globals.css'

import { ThemeModeScript } from 'flowbite-react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import type { ReactNode } from 'react'

import { cn } from '~/utils/classnames'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={cn(inter.className, 'bg-zinc-900 text-zinc-100')}>{children}</body>
    </html>
  )
}
